### ISSUE TITLE
Plan for Release or Tag?

### ISSUE THREAD

**Issue by laryn** [Lullabot/tabled#3]
Thanks for this plugin! I'm testing it out as a simple Backdrop module to make it easy for less technical people to simply download the module and enable it, and get this accessibility/functionality up and running with the sensible defaults you've created. (I'm implementing it on non-admin routes only and allowing an opt-out by not including tables with an `.untabled` class).

I was wondering if you have a plan for making an initial release or tag. To make this work as seamlessly as possible for users who may be adding the module with the project installer through their website UI, I am bundling the plugin and would prefer to bundle a specific release or tag to make it easy to see where we are in the future. If you don't plan to do so, I can release as is.

I've also included credits to you and your team in the README. Please let me know if this is correct or if you'd like me to modify anything here:

> The Tabled plugin was developed and is maintained by a team at [Lullabot](https://lullabot.com), including [Javier Reartes](https://github.com/javi-er),  Stephanie Ganzer and Kat Shaw.  The plugin is released under the GPL v3 license.

https://github.com/backdrop-contrib/tabled

**Comment by Javi-er** [comment]
Hi @laryn, sorry for the late response, I wasn't following messages here. That's amazing, I have created a new release just now so you can track changes. I have also changed the license to GPL v2.0 so it's compatible with Drupal licensing. The credit note looks good to me, but please update the license version.

Since we published this plugin, I have also worked on a Drupal 10 module that includes a CKE5 plugin with some small accessibility improvements over the default CKE table plugin in case it's helpful for you.
https://www.drupal.org/project/ckeditor_responsive_table

**Comment by laryn** [comment]
Great, thanks!
